name: Dispatch license updated event to deimonn.github.io

on:
  push:
    branches:
      - master
    paths:
      - LICENSE

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event
        run: |
          curl -L \
               -X POST \
               -H 'Accept: application/vnd.github+json' \
               -H "Authorization: Bearer ${{ secrets.DISPATCH_PAT }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/deimonn/deimonn.github.io/dispatches \
               -d '{"event_type":"update-licenses"}'
